/* Note This file is generated by tools, don't modify it */
#include <stdio.h>
#include <string.h>
extern int Printf(const char *fmt, ...);

int version(void)
{
    Printf("\n############################################\n");
    Printf("# RTOS: luos, version: 2023-06-27 09:24:48 #\n");
    Printf("############################################\n\n");

    return 0;
}
