/* Note This file is generated by tools, don't modify it */
#include <stdio.h>
#include <string.h>

int version(void)
{
    printf("\n############################################\n");
    printf("# RTOS: luos, version: 2023-06-09 17:50:36 #\n");
    printf("############################################\n\n");

    return 0;
}
